---
templates:

  cache_key: &cache_key
    key: v1-{{ checksum "setup.py" }}-{{ checksum "circle.yml" }}

version: 2
jobs:

  test:
    working_directory: ~/marketing-cloud-proxy
    docker:
      - image: circleci/python:3.7
    environment:
      CC_REPORTER: "https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64"
    steps:
      - checkout
      - restore_cache:
          <<: *cache_key
      - run:
          name: Install Requirements
          command: |
            if [[ ! -d ~/.venv ]]; then
              python -m venv ~/.venv
              . ~/.venv/bin/activate
              pip install --upgrade pip setuptools
              pip install wheel
              pip install -e .
              python setup.py test_requirements
              curl -L "$CC_REPORTER" > ~/.venv/bin/cc-test-reporter
              chmod +x ~/.venv/bin/cc-test-reporter
            fi
          environment:
            CFLAGS: "-I/var/task/include -L/var/task/lib"
      - run:
          name: Test
          command: |
            . ~/.venv/bin/activate
            cc-test-reporter before-build
            pytest
      - save_cache:
          <<: *cache_key
          paths:
            - ~/.venv
            - ~/marketing-cloud-proxy/marketing-cloud-proxy.egg-info
            - ~/marketing-cloud-proxy/.eggs
            - ~/marketing-cloud-proxy/bin

  build_lambda:
    working_directory: ~/marketing-cloud-proxy
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Build Lambda
          command: |
            mkdir -p workspace/pkg

            # https://github.com/pyca/cryptography/issues/6391
            pip install \
              --platform manylinux2010_x86_64 \
              --implementation cp \
              --python 3.7 \
              --only-binary=:all: --upgrade \
              --target workspace/pkg \
              cryptography

            pip install . -t workspace/pkg
      - persist_to_workspace:
          root: workspace
          paths:
            - pkg

  deploy_lambda:
    working_directory: ~/marketing-cloud-proxy
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - attach_workspace:
          at: workspace
      - restore_cache:
          <<: *cache_key
      - run:
          name: Deploy Lambda
          command: |
            if [[ "${CIRCLE_BRANCH}" == "main" || "${CIRCLE_TAG}" == "demo" ]]; then
              export ENV=demo
              export TAG=demo
              export DEMO_RELEASE="$CIRCLE_SHA1"
            elif echo "$CIRCLE_TAG" | grep -q "v[0-9]\+\.[0-9]\+\.[0-9]\+"; then
              export ENV=prod
              export TAG=$CIRCLE_TAG
              export PROD_RELEASE="$TAG"
            else
              exit 1
            fi
            if [[ ! -d ~/.venv ]]; then
              python -m venv ~/.venv
              . ~/.venv/bin/activate
              pip install --upgrade pip setuptools
              pip install wheel
            fi
            pip install -e .
            python setup.py deploy \
              --environment=$ENV \
              --function-name=marketing-cloud-proxy \
              --function-handler=marketing_cloud_proxy.handler \
              --package-dir=workspace/pkg

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
          context: "AWS Deploy"
      - build_lambda:
          requires:
            - test
          filters:
            tags:
              only:
                - /^v[0-9]+\.[0-9]+\.[0-9]+/
                - demo
            branches:
              only: main
      - deploy_lambda:
          requires:
            - build_lambda
          context: "AWS Deploy"
          filters:
            tags:
              only:
                - /^v[0-9]+\.[0-9]+\.[0-9]+/
                - demo
            branches:
              only: main


experimental:
  notify:
    branches:
      only:
        - main
